# reconciliation.properties - ISPW Report Column Bounds & Thresholds
recon.ispw.ci_type.bounds = 0,4
recon.ispw.ci_name.bounds = 5,13
recon.ispw.env_lvl.bounds = 14,22
recon.ispw.sr.bounds = 30,40
recon.ispw.user.bounds = 41,47
recon.ispw.action.bounds = 55,65
recon.ispw.min_line_length = 65
