# teams.properties - Team Mappings & Leads
unassigned_backlog_assignee_id = LINCOLN.TODD.ALAN

team.unassigned.name = Unassigned backlog
team.unassigned.lead = LINCOLN.TODD.ALAN
team.unassigned.members = LINCOLN.TODD.ALAN

team.lifeline.name = Team Lifeline
team.lifeline.lead = HULL.JAMES.DOUGLAS
team.lifeline.component = Team Lifeline
team.lifeline.id = 157
team.lifeline.members = HULL.JAMES.DOUGLAS

team.decisive.name = Team Decisive
team.decisive.lead = ABERNATHY.DAMON.LAMAR
team.decisive.component = Team Decisive
team.decisive.id = 147
team.decisive.members = ABERNATHY.DAMON.LAMAR

team.renegades.name = Team Renegades
team.renegades.lead = CROSSETT.OLIVIA
team.renegades.component = Team Renegades
team.renegades.id = 156
team.renegades.members = CROSSETT.OLIVIA

team.fulcrum.name = Team Fulcrum
team.fulcrum.lead = ANDERSON.CHAD.D
team.fulcrum.component = Team Fulcrum
team.fulcrum.id = 143
team.fulcrum.members = ANDERSON.CHAD.D

team.fidelis.name = Team Fidelis
team.fidelis.lead = JOHNSON.TONY.E
team.fidelis.component = Team Fidelis
team.fidelis.id = 149
team.fidelis.members = JOHNSON.TONY.E
